name:                sweeper
version:             0.1.0.0
github:              "githubuser/sweeper"
license:             BSD3
author:              "John Carbeck"
maintainer:          "carbeckj@tcd.ie"
copyright:           "2019 John Carbeck"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sweeper#readme>

dependencies:
- base >= 4.7 && < 5
- matrix
- random
- random-shuffle
- scotty
- blaze-html
- blaze-markup
- text
- aeson
- vector
- optparse-generic



library:
  source-dirs: src

executables:
  sweeper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sweeper

tests:
  sweeper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sweeper
